### ISSUE TITLE
Fn keys question

### ISSUE THREAD

**Issue by AlexFullmoon** [Baio1977/Lenovo-Thinkpad-T14#10]
Hello. Sorry for contacting you through github issues, but yours seem to be one of few up-to-date Thinkpad builds. I've got X1 Yoga 5, which is rather similar. As you report all Fn keys working, some questions:

Do you have working Fn-F7 key? For me it shows notification but does nothing. Is there some other setting required?

Do you have working Fn-F9 through Fn-F12 keys. Fn-Tab, Fn-PrtSc? YogaSMC shows notification like "Event 0x1317:0". Is there maybe a way to assign that to some script or shortcut?

**Comment by AlexFullmoon** [comment]
Well, YogaSMC development went inactive, it seems, which is why I'm asking around.

Thank you, anyway.

**Comment by Baio1977** [comment]
https://github.com/MSzturc/ThinkpadAssistant test this App , remove YogaSMC
