### ISSUE TITLE
Can't install Sonoma on T14 Gen1 20S1

### ISSUE THREAD

**Issue by dolence** [Baio1977/Lenovo-Thinkpad-T14#13]
This is supposed to work with the latest Sonoma? I'm trying to boot from USB with Sonoma boot recovery downloaded using macrecovery python script without success. Is there anything special that need to be done for Sonoma? It gets stuck as soon as the Apple logo shows on screen with the progression bar at the very beggining.

EDIT: since I'm on linux, I don't think using a full image is possible.

**Comment by dolence** [comment]
I was able to install Ventura, only wifi didn't worked. Any tips? Is it safe to update to Sonoma?

**Comment by Baio1977** [comment]
The PC belongs to my Uncle, he still has Sonoma 14.3 I think, some things have changed since version 14.5+ probably the EFI still needs to be updated.

**Comment by dolence** [comment]
I got wi-fi working by usingthe correct kext for Ventura. Once I get a second NVMe I will try Sonoma again, keeping the old as backup. Thank you for your help and for sharing your work.

**Comment by dolence** [comment]
> The PC belongs to my Uncle, he still has Sonoma 14.3 I think, some things have changed since version 14.5+ probably the EFI still needs to be updated.
> https://github.com/Baio1977/Lenovo-Thinkpad-T14/releases/tag/V1
> Test this EFI on Sonoma 14.5

Tried this EFI folder and worked flawlessly for updating my system. There is just one thing left to be done: my keyboard is Brazilian Portuguese version. The key with ?/ characters doesn't output anything. Any thoughts?
Also, os there any way to map the PrtSc to take screenshots?

![20240708_163439.jpg](https://github.com/Baio1977/Lenovo-Thinkpad-T14/assets/5223003/428f3ca9-4175-4769-a816-c8165499283f)

**Comment by Baio1977** [comment]
https://github.com/oq-x/languages-opencore/blob/main/languages.txt

[128] pt_BR - Brazilian-ABNT2 - 70742D42523A313238
[72] pt_BR - Brazilian - Pro - 70742D42523A3732
[71] pt_BR - Brazilian - 70742D42523A3731

In configplist:
![Screenshot 2024-07-12 alle 20 14 27](https://github.com/user-attachments/assets/27c1e911-c6e3-4a17-84f7-c23387cc6d8a)

Change this:
![Screenshot 2024-07-12 alle 20 23 38](https://github.com/user-attachments/assets/bf4d6ba2-4d4d-4292-8605-f1ac249d2e38)

**Comment by dolence** [comment]
I've tried the 3 options for the keyboard but it still not working. I noticed the key normally located to the left of the shift on regular ABNT2 keyboard on this laptop it's located where should be the second Ctrl key (the right one) and it indeed work as I could check on terminal. Do you have any suggetion to remap this key to work as indeed?
