### ISSUE TITLE
Battery Life

### ISSUE THREAD

**Issue by xxx090909** [Baio1977/Lenovo-Thinkpad-T14#16]
Hello, I have a T14s. Would like to install Sonoma or Sequoia. With my old T460s, the battery life was not so good. Can you tell me how she is now under Sonoma or Sequoia?

**Comment by Baio1977** [comment]
Battery consumption is not bad, obviously on Windows the battery is managed better than on Mac.

**Comment by xxx090909** [comment]
Hello, thanks for the answer. I'll give it a try. With my T460s it wasn't even 3 hours and hibernation never really worked.
If I get 6 hours with the T14, that would be enough.
