### ISSUE TITLE
Support for Sequoia?

### ISSUE THREAD

**Issue by vickmansystems** [Baio1977/Lenovo-Thinkpad-T14#17]
Hello, this isn't so much an issue as it is a request to see if you'll update the EFI to support macOS 15? This is an amazingly well-done project for the Lenovo T14, especially to have all of the hotkeys and USB-C hotplug working in macOS 14, it's great!

Really appreciate the work put into this, thanks again!

**Comment by Baio1977** [comment]
Can you test the latest EFI release??
If so, attach the ioreg of the new EFI, thanks

**Comment by vickmansystems** [comment]
I just realized you put out a new release! I've tried it and everything seems ok, but the WiFi isn't working. I can see that based on the config, it looks like Heliport is required for this to work? I know that Airportitlwm still needs some work from Sonoma 14.4 onwards to allow WiFi to work without using the OCLP method. Either way, I've attached my IOReg. Thanks!
[Lenovo T14 G1.zip](https://github.com/user-attachments/files/17740620/Lenovo.T14.G1.zip)

**Comment by Baio1977** [comment]
<img width="396" alt="Screenshot 2024-11-16 alle 12 25 16" src="https://github.com/user-attachments/assets/3c72089a-422d-4d91-8506-91def8b80911">

you have wi fi turned off, see in bios or turn it on via key combination

**Comment by vickmansystems** [comment]
Hello, I’ve just had a look and I cannot see anywhere that the wifi is disabled? I know it’s not disabled in the bios as I have a working instance of Sonoma on a different NVMe drive. And the F8 key does nothing? From your screenshot, I see the Realtek controller and thunderbolt controller. Am I missing something? Thanks again!
________________________________
