### ISSUE TITLE
Internal Microphone not Working

### ISSUE THREAD

**Issue by askwakhid** [Baio1977/Lenovo-Thinkpad-T14#2]
Hi,

Thank you for ThinkPad T14 Gen 1 EFI.
Btw, I use your EFI on my ThinkPad T14 Gen 1 but my machine is i5 version.

Internal Microphone not Working, any suggestions for fix this microphone issue ?
I read on Readme, your microphone is working.

Thank you.

**Comment by Baio1977** [comment]
On Laptop HW CPU 10 Gen internal mic NO longer works with ALC , so I bought an external USB Mic

**Comment by askwakhid** [comment]
Hi,

Ah Noted, thank you for information.

**Comment by askwakhid** [comment]
Dear Baio1977,

Im sorry, I have question again.

What you create configuration for CPU Clock Limitation ?
On my T14 CPU clock locked on base clock, its mean Turbo Bost cant active.
I try disable CPUFriend, ect but still cant figure it out.

Thank you.
