### ISSUE TITLE
Bluetooth, sleep and wake problems

### ISSUE THREAD

**Issue by philions** [Baio1977/Lenovo-Thinkpad-T14#3]
I've installed ventura and found issues as follow:
1. after installation, wifi can see networks but can't connect, bluetooth can see devices but also can't connect, following https://github.com/Baio1977/OC-Little-Translated/tree/main/10_Kexts_Loading_Sequence_Examples, I adjust wifi kext order, now wifi is working, but bluetooth remain same problem.
2. logout system, after about 2 or 3 seconds, screen blackout and can't bright again, all I can do is that pushing power button and reboot computer.

**Comment by Baio1977** [comment]
To wake up the PC lower the screen wait for it to go to sleep and raise the screen, it should wake up, or try pressing the power button for a few seconds.

**Comment by philions** [comment]
I do as you say, but screen still remain black, pressing power button still don't work, I search net and found HibernationFixup.kext, does it help?

**Comment by Baio1977** [comment]
![Screenshot 2023-02-20 alle 20 06 27](https://user-images.githubusercontent.com/59058746/220182993-4c9095a1-a726-470d-ba89-f8f5038f011e.png)
With my EFI you have to set as in the picture, use hackintool
