### ISSUE TITLE
External Display Can't Reach 60HZ

### ISSUE THREAD

**Issue by dolams2020** [Baio1977/Lenovo-Thinkpad-T14#4]
1. For Hdmi Port
2. For TypeC Port
3. For DP To TypeC
I have try this in 3 ways, also I install EasyRes, but's can't do even retina2x 1080P for 60HZ, 60HZ only support 2K for normal 1x, and 720P for retina2x.

ps. external display and line are well, I tested in Microsoft 11, supported 4k 60Hz.

**Comment by Baio1977** [comment]
T14 is my Uncle's PC, tonight I'll check the EFI but for the tests I have to get the PC back.
I tested on Samsung QLed.
The IGPU patch probably needs to be finished.

**Comment by dolams2020** [comment]
> T14 is my Uncle's PC, tonight I'll check the EFI but for the tests I have to get the PC back.
> I tested on Samsung QLed.
> The IGPU patch probably needs to be finished.

Thanks. For search the internet I have try many way to solve this problem, but all failed.
Most uesful way is delete key-value framebuffer-stolenmem in config.plist, then reboot will enable hidpi.

waiting you good news 0.0

**Comment by Baio1977** [comment]
I took the T14 again, updated OC and OS and did various tests.
Ultima EFI improves HIPDI capabilities based on your testing.
See to adjust Bios settings.
