### ISSUE TITLE
An error occurred (hangs) while installing macOS

### ISSUE THREAD

**Issue by LeLuyen** [Baio1977/Lenovo-Thinkpad-T14#5]
While installing macOS, MacOS hangs in the time left.

See attachment files.
![b3c4e7662462f93ca073](https://user-images.githubusercontent.com/2620445/223904229-4dec4805-4485-4f88-8c6d-1adc6d7af7a3.jpg)
![209276a8b7ac6af233bd](https://user-images.githubusercontent.com/2620445/223904244-b702fd0f-ab1a-4ec9-91d7-81f2e46a10c5.jpg)

**Comment by Baio1977** [comment]
Model make NVME???
Probably not compatible with Hackintosh

**Comment by LeLuyen** [comment]
Hi @Baio1977 B
Same you,

I has change other hard driver and install ok,

But when boot again, i have an error about AirportItlwm_Ventura.kext
![77c9103d9c34416a1825](https://user-images.githubusercontent.com/2620445/224200335-cbcfd5e4-f8e0-4375-9f7b-af8b12712407.jpg)

**Comment by Baio1977** [comment]
What OS are you installing???
You probably need to match the WI-FI kext with the kext for BigSur
[AirportItlwm_BigSur.kext.zip](https://github.com/Baio1977/Lenovo-Thinkpad-T14/files/10941939/AirportItlwm_BigSur.kext.zip)

**Comment by LeLuyen** [comment]
Hi @Baio1977 

I got it

Thanks you
