### ISSUE TITLE
panic diags file unavailable. painic occurred prior to initiallization

### ISSUE THREAD

**Issue by peng-heng** [Baio1977/Lenovo-Thinkpad-T14#8]
T14 gen1
CPU: i5 1021U   
BIOS V1.17
BASE IMAGE:   macOS Monterey 12.6 21G115 Installer for OpenCore 0.8.4 and CLOVER 5148 and FirPE

Hello, may I ask if this issue is caused by the type of disk?

![img_v2_d6974369-b8fb-41c5-a610-504888979e0g](https://github.com/Baio1977/Lenovo-Thinkpad-T14/assets/11962364/42eb5552-caa3-48ff-a2c6-8a8977fe9c95)
![img_v2_b7ef563a-0db6-434f-ba11-592635eed9ag](https://github.com/Baio1977/Lenovo-Thinkpad-T14/assets/11962364/63905b3f-cc40-44f6-a98c-fe7e89661517)

**Comment by Baio1977** [comment]
Sure you have an SSD NOT compatible with Apple OS
