### ISSUE TITLE
Mic and bluetooth not working (on Ventura 13.4.1)

### ISSUE THREAD

**Issue by funder7** [Baio1977/Lenovo-Thinkpad-T14#9]
Hi,
Thank you for your work on this configuration :-)

I'm running Ventura as stated in the title, with the latest OpenCore (0.9.3). 
In my case, bluetooth doesn't work, and I'm having problems with wifi not always connecting after sleep.
The last problem that I've noticed is that the internal microphone is not working. I've read online that this particular mic is not supported by Apple, but your Readme reports it as working.. do you have more info about this? 

I can send a PR with the new `Config.plist` for OC 0.9.3 if you want

Cheers

**Comment by Baio1977** [comment]
Post all EFI + ioreg ,[For Mic](https://www.amazon.it/gp/product/B08LH4XPM1/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8&psc=1)

**Comment by codecompliant** [comment]
Can you confirm if the internal mic (screen) is working as described?

**Comment by Baio1977** [comment]
> Puoi confermare se il microfono interno (schermo) funziona come descritto?

Mic internal NO work ....

**Comment by funder7** [comment]
Sorry guys, I had to switch back to windows, unfortunately I didn't receive the notifications for your replies and I don't have the configurations files anymore. 

Anyway the configuration published in this project is ok, I've just opened it with [OpenCore configurator](https://mackie100projects.altervista.org/download-opencore-configurator/), which adds the missing keys automatically. You can do the same. 

My mic wasn't working, as stated in the title. Cheers
